[metadata]
name = siestaApp
version = 0.0.1
description = Preliminary app to run Siesta calculations, developed at the nanotech@surfaces laboratory, Empa.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/nanotech-empa/aiidalab-empa-siesta
author = Carlo A. Pignedoli
author_email = c.pignedoli@gmail.com
license = MIT
license_files = LICENSE.txt
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Science/Research
    License :: OSI Approved :: MIT License
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Operating System :: OS Independent
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Chemistry
    Topic :: Scientific/Engineering :: Physics
    Topic :: Scientific/Engineering :: Materials Science
    Framework :: Jupyter

project_urls =
    Logo = https://raw.githubusercontent.com/nanotech-empa/aiidalab-empa-siesta/master/miscellaneous/logos/empa.png
    Documentation = https://github.com/nanotech-empa/aiidalab-empa-siesta/#readme
    Bug Tracker = https://github.com/nanotech-empa/aiidalab-empa-siesta/issues

[options]
packages = find:
install_requires =
    aiida-core~=2.7
    aiida-nanotech-empa>=1.0.0b12
    aiidalab-widgets-base[smiles]>=2.3.1,<3.0
    aiidalab-widgets-empa>=0.2.2
    ase>=3.24
    anywidget==0.9.13
python_requires = >=3.9

[options.extras_require]
dev =
    bumpver==2022.1119
    pre-commit~=2.20
    black
    isort
    flake8
    pytest
    build

[aiidalab]
title = Empa nanotech@surfaces Laboratory - siesta App

[flake8]
ignore =
    E501
    W503
    E203
per-file-ignores =
    tests/*: U100, U101

[bumpver]
current_version = "0.0.1"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "Bump version {old_version} -> {new_version}."
commit = True
tag = True
push = True

[bumpver:file_patterns]
setup.cfg =
    current_version = "{version}"
    version = {pep440_version}
